const types ={
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_RECEIVE: 'SIGNUP_RECEIVE',
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_RECEIVE: 'AUTH_RECEIVE',
  AUTH_RESET: 'AUTH_RESET',
  AUTH_STATUS: 'AUTH_STATUS'
};

export {
  types
}
