const types ={
  SIGNUP_REQUEST   : 'SIGNUP_REQUEST',
  SIGNUP_RECEIVE   : 'SIGNUP_RECEIVE',
  SIGNUP_RECEIVE_ERROR: 'SIGNUP_RECEIVE_ERROR',
  AUTH_REQUEST     : 'AUTH_REQUEST',
  AUTH_RECEIVE     : 'AUTH_RECEIVE',
  AUTH_RESET       : 'AUTH_RESET',
  AUTH_STATUS      : 'AUTH_STATUS',
  TODO_LIST_REQUEST: 'TODO_LIST_REQUEST',
  TODO_LIST_RECEIVE: 'TODO_LIST_RECEIVE',
  TODO_LIST_ERROR  : 'TODO_LIST_ERROR',
  TODO_ADD         : 'TODO_ADD',
  TODO_REMOVE      : 'TODO_REMOVE',
  TODO_ARCHIVE     : 'TODO_ARCHIVE',
  TODO_UPDATE      : 'TODO_UPDATE'
};

export {
  types
}
